# Generated by Django 5.2.16 on 2026-10-08 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_dropbox_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Period name shown on the home page.', max_length=50)),
                ('start_month', models.PositiveSmallIntegerField(help_text='First month (1-12).')),
                ('end_month', models.PositiveSmallIntegerField(help_text='Last month (1-12).')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order on the home page.')),
                ('profile', models.ForeignKey(help_text='Workspace that owns this period.', on_delete=django.db.models.deletion.CASCADE, related_name='home_periods', to='profiles.profile')),
            ],
            options={
                'ordering': ['sort_order', 'start_month', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_home_period_name'), models.CheckConstraint(condition=models.Q(('start_month__gte', 1), ('start_month__lte', 12)), name='home_period_start_range'), models.CheckConstraint(condition=models.Q(('end_month__gte', 1), ('end_month__lte', 12)), name='home_period_end_range'), models.CheckConstraint(condition=models.Q(('start_month__lte', models.F('end_month'))), name='home_period_order')],
            },
        ),
    ]
