# Generated by Django 5.2.16 on 2026-09-08 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category_alter_expense_farm'),
        ('farm', '0002_profile'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name used to group tasks.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task category was created.')),
                ('profile', models.ForeignKey(editable=False, help_text='Profile that owns this task category.', on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to='profiles.profile')),
            ],
            options={
                'verbose_name_plural': 'task categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreePlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(help_text='Number of trees of this type on the farm.')),
                ('planted_on', models.DateField(blank=True, help_text='Optional planting date.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about these trees.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last changed.')),
                ('farm', models.ForeignKey(help_text='Farm these trees belong to.', on_delete=django.db.models.deletion.PROTECT, related_name='tree_plantings', to='farm.farm')),
                ('profile', models.ForeignKey(editable=False, help_text='Profile that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='tree_plantings', to='profiles.profile')),
            ],
            options={
                'ordering': ['farm__title', 'tree_type__name'],
            },
        ),
        migrations.CreateModel(
            name='FarmTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of the task.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Additional details about the task.')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Date on which the task occurred.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the task was last changed.')),
                ('expense', models.ForeignKey(blank=True, help_text='Optional expense linked to this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tasks', to='expenses.expense')),
                ('farm', models.ForeignKey(help_text='Farm this task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='farm.farm')),
                ('profile', models.ForeignKey(editable=False, help_text='Profile that owns this task.', on_delete=django.db.models.deletion.CASCADE, related_name='farm_tasks', to='profiles.profile')),
                ('category', models.ForeignKey(help_text='Task category.', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='farm.taskcategory')),
                ('planting', models.ForeignKey(blank=True, help_text='Optional tree group this task targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='farm.treeplanting')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name used to group trees.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the tree type was created.')),
                ('profile', models.ForeignKey(editable=False, help_text='Profile that owns this tree type.', on_delete=django.db.models.deletion.CASCADE, related_name='tree_types', to='profiles.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='tree_type',
            field=models.ForeignKey(help_text='Type of tree.', on_delete=django.db.models.deletion.PROTECT, related_name='plantings', to='farm.treetype'),
        ),
        migrations.AddConstraint(
            model_name='taskcategory',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='unique_task_category_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='treetype',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='unique_tree_type_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='treeplanting',
            constraint=models.UniqueConstraint(fields=('farm', 'tree_type'), name='unique_tree_type_per_farm'),
        ),
    ]
