# Generated by Django 5.2.16 on 2026-09-08 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_contacts_profile_fields'),
        ('farm', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='Expense category.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='farm',
            field=models.ForeignKey(help_text='Farm this expense belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='farm.farm'),
        ),
    ]
