# Generated by Django 5.2.16 on 2026-09-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category_alter_expense_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived expenses stay in lists and reports but are hidden from task dropdowns.'),
        ),
    ]
