# Generated by Django 5.2.4 on 2026-10-03 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_is_archived'),
        ('farm', '0004_tree_inventory_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm this expense belongs to. Leave empty to split across all farms by tree count.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='farm.farm'),
        ),
    ]
