# Generated by Django 5.2.4 on 2026-10-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_farm_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='Unpaid expenses appear under obligations.'),
        ),
    ]
