# Generated by Django 5.2.4 on 2026-10-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_is_paid'),
        ('farm', '0004_tree_inventory_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_basis',
            field=models.CharField(choices=[('trees', 'Trees'), ('tree_type', 'Tree variety'), ('area', 'Area (stremmata)'), ('equal', 'Equal')], default='trees', help_text='How a shared (farm-less) expense is split across farms.', max_length=9),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_tree_type',
            field=models.ForeignKey(blank=True, help_text='Tree variety used when the split basis is a single variety.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_expenses', to='farm.treetype'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm this expense belongs to. Leave empty to split across all farms by the selected basis.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='farm.farm'),
        ),
    ]
