# Generated by Django 5.2.4 on 2026-10-06 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0004_tree_inventory_history'),
        ('incomes', '0005_income_is_archived'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Harvest year.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Harvested quantity.', max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kg'), ('tn', 'Tn'), ('l', 'L')], default='kg', help_text='Quantity unit.', max_length=2)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this harvest.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last changed.')),
                ('farm', models.ForeignKey(help_text='Farm this production belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='farm.farm')),
                ('profile', models.ForeignKey(editable=False, help_text='Profile that owns this production.', on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='profiles.profile')),
                ('tree_type', models.ForeignKey(help_text='Tree type harvested.', on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='farm.treetype')),
            ],
            options={
                'ordering': ['-year', 'farm__title', 'tree_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionIncomeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_links', to='incomes.income')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_links', to='production.production')),
                ('profile', models.ForeignKey(editable=False, help_text='Profile that owns this link.', on_delete=django.db.models.deletion.CASCADE, related_name='production_income_links', to='profiles.profile')),
            ],
            options={
                'ordering': ['production_id', 'income_id'],
            },
        ),
        migrations.AddField(
            model_name='production',
            name='incomes',
            field=models.ManyToManyField(blank=True, related_name='productions', through='production.ProductionIncomeLink', to='incomes.income'),
        ),
        migrations.AddConstraint(
            model_name='productionincomelink',
            constraint=models.UniqueConstraint(fields=('production', 'income'), name='unique_production_income_link'),
        ),
        migrations.AddConstraint(
            model_name='production',
            constraint=models.UniqueConstraint(fields=('farm', 'year', 'tree_type'), name='unique_production_per_farm_year_type'),
        ),
    ]
