# Generated by Django 5.2.16 on 2026-09-08 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_profile'),
        ('incomes', '0002_contacts_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(help_text='Income category.', on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='incomes.incomecategory'),
        ),
        migrations.AlterField(
            model_name='income',
            name='farm',
            field=models.ForeignKey(help_text='Farm this income belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='farm.farm'),
        ),
    ]
