# Generated by Django 5.2.16 on 2026-09-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0004_income_farm_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived incomes stay in lists and reports but are hidden from selection dropdowns.'),
        ),
    ]
